# Generated by Django 4.2.16 on 2024-11-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_topic_owner'),
        ('question', '0002_remove_question_question_text_remove_question_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question', to='topic.topic'),
        ),
    ]
