# Generated by Django 4.2.16 on 2025-01-04 10:44

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=question.models.get_image_upload_to),
        ),
    ]
