# Generated by Django 4.2.16 on 2024-12-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='point',
            new_name='score',
        ),
    ]
