# Generated by Django 4.2.16 on 2024-11-21 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
